#include "changelog.h"
#include "settings_store.h"

namespace Config {

namespace {
    // Reihenfolge MUSS zu I18n::TABLES (i18n.cpp) und damit zu
    // SettingsStore::language() passen: EN, DE, FR, TR, ES, IT, PT.
    constexpr uint8_t CHANGELOG_LANG_COUNT = 7;

    const char* const CHANGELOG_EN =
        "- New: Portuguese (Brazilian) added as the seventh language\n"
        "- New: added \"Red\" and \"Purple\" color themes - the three "
        "color buttons in the Radar Display menu were merged into a "
        "single \"Colors\" button that opens a selection screen with "
        "all five themes\n"
        "- Changed: the emergency alarm now blinks in a real Morse "
        "SOS pattern (3 short, 3 long, 3 short), so it stays clearly "
        "recognizable as an emergency even with the Red color theme "
        "active\n"
        "- Changed: the update-available LED signal now blinks white "
        "instead of magenta\n"
        "- New: added and explained the military/government and "
        "Heavy aircraft symbols in the altitude color legend\n"
        "- Fix: rain on the screensaver used to sit below the logo/"
        "clock instead of above it\n"
        "- New: location preset name entry now supports special "
        "characters (e.g. \"Zürich\", \"São Paulo\")\n"
        "- Improved: added Â/Î/Ë/Û to the address special-character "
        "keyboard\n"
        "- Fix: fixed a keyboard layout overflow (the bottom action "
        "row was cut off on the expanded special-character "
        "keyboard)\n"
        "- Fix: the language selection list (initial setup + menu) "
        "now uses a dynamic row height, so no screen overflow "
        "happens even with 7 languages";

    const char* const CHANGELOG_DE =
        "- Neu: Portugiesisch (brasilianisch) als siebte Sprache "
        "hinzugefuegt\n"
        "- Neu: Farbthemen \"Rot\" und \"Lila\" hinzugefuegt - die "
        "drei Farb-Buttons im Radar-Darstellungs-Menue wurden zu "
        "einem einzigen \"Farben\"-Button zusammengefasst, der einen "
        "Auswahlscreen mit allen fuenf Themen oeffnet\n"
        "- Geaendert: der Notfall-Alarm blinkt jetzt im echten "
        "Morse-SOS-Muster (3 kurz, 3 lang, 3 kurz), damit er auch bei "
        "aktivem Rot-Farbthema eindeutig als Notfall erkennbar "
        "bleibt\n"
        "- Geaendert: das Update-Verfuegbar-LED-Signal blinkt jetzt "
        "in Weiss statt Magenta\n"
        "- Neu: Militaer-/Behoerden- und Heavy-Flugzeug-Symbol in der "
        "Hoehen-Farben-Legende ergaenzt und erklaert\n"
        "- Fix: der Regen-Effekt auf dem Ruhebildschirm lag vorher "
        "unter Logo/Uhrzeit statt darueber\n"
        "- Neu: die Standort-Preset-Namenseingabe unterstuetzt jetzt "
        "Sonderzeichen (z.B. \"Zürich\", \"São Paulo\")\n"
        "- Verbessert: die Adress-Sonderzeichen-Tastatur wurde um "
        "Â/Î/Ë/Û ergaenzt\n"
        "- Fix: ein Tastatur-Layout-Ueberlauf behoben (die unterste "
        "Aktionszeile war bei der erweiterten Sonderzeichen-Tastatur "
        "abgeschnitten)\n"
        "- Fix: die Sprachauswahl-Liste (Ersteinrichtung + Menue) "
        "verwendet jetzt eine dynamische Zeilenhoehe, damit auch bei "
        "7 Sprachen kein Bildschirmueberlauf entsteht";

    const char* const CHANGELOG_FR =
        "- Nouveau : le portugais (bresilien) ajoute comme septieme "
        "langue\n"
        "- Nouveau : ajout des themes de couleur \"Rouge\" et "
        "\"Violet\" - les trois boutons de couleur du menu Affichage "
        "radar ont ete regroupes en un seul bouton \"Couleurs\" qui "
        "ouvre un ecran de selection avec les cinq themes\n"
        "- Modifie : l'alarme d'urgence clignote desormais selon un "
        "vrai motif Morse SOS (3 courts, 3 longs, 3 courts), pour "
        "rester clairement reconnaissable comme urgence meme avec le "
        "theme Rouge actif\n"
        "- Modifie : le signal LED de mise a jour disponible "
        "clignote desormais en blanc au lieu de magenta\n"
        "- Nouveau : ajout et explication des symboles militaire/"
        "gouvernemental et avion Heavy dans la legende des couleurs "
        "d'altitude\n"
        "- Correction : la pluie sur l'ecran de veille se trouvait "
        "auparavant sous le logo/l'heure au lieu d'etre au-dessus\n"
        "- Nouveau : la saisie du nom des presets de localisation "
        "prend desormais en charge les caracteres speciaux (ex. "
        "\"Zürich\", \"São Paulo\")\n"
        "- Ameliore : ajout de Â/Î/Ë/Û au clavier de caracteres "
        "speciaux pour les adresses\n"
        "- Correction : correction d'un debordement de mise en page "
        "du clavier (la ligne d'action du bas etait coupee sur le "
        "clavier de caracteres speciaux etendu)\n"
        "- Correction : la liste de selection de la langue "
        "(configuration initiale + menu) utilise desormais une "
        "hauteur de ligne dynamique, afin qu'aucun debordement "
        "d'ecran ne se produise meme avec 7 langues";

    const char* const CHANGELOG_TR =
        "- Yeni: yedinci dil olarak Portekizce (Brezilya) eklendi\n"
        "- Yeni: \"Kırmızı\" ve \"Mor\" renk temaları eklendi - Radar "
        "Görünümü menüsündeki üç renk düğmesi, beş temanın tümünü "
        "içeren bir seçim ekranı açan tek bir \"Renkler\" düğmesinde "
        "birleştirildi\n"
        "- Değiştirildi: acil durum alarmı artık gerçek bir Mors SOS "
        "düzeninde yanıp sönüyor (3 kısa, 3 uzun, 3 kısa), böylece "
        "Kırmızı renk teması etkinken bile net bir şekilde acil "
        "durum olarak tanınabiliyor\n"
        "- Değiştirildi: güncelleme mevcut LED sinyali artık magenta "
        "yerine beyaz yanıp sönüyor\n"
        "- Yeni: yükseklik renk lejantına askeri/resmi ve Heavy uçak "
        "simgeleri eklendi ve açıklandı\n"
        "- Düzeltme: ekran koruyucudaki yağmur önceden logo/saatin "
        "üstünde değil altında görünüyordu\n"
        "- Yeni: konum ön ayarı adı girişi artık özel karakterleri "
        "destekliyor (ör. \"Zürich\", \"São Paulo\")\n"
        "- İyileştirme: adres özel karakter klavyesine Â/Î/Ë/Û "
        "eklendi\n"
        "- Düzeltme: bir klavye düzeni taşması giderildi "
        "(genişletilmiş özel karakter klavyesinde en alttaki işlem "
        "satırı kesiliyordu)\n"
        "- Düzeltme: dil seçim listesi (ilk kurulum + menü) artık "
        "dinamik satır yüksekliği kullanıyor, böylece 7 dilde bile "
        "ekran taşması olmuyor";

    const char* const CHANGELOG_ES =
        "- Novedad: portugués (brasileño) añadido como séptimo "
        "idioma\n"
        "- Novedad: añadidos los temas de color \"Rojo\" y \"Morado\" "
        "- los tres botones de color del menú Pantalla del radar se "
        "unificaron en un único botón \"Colores\" que abre una "
        "pantalla de selección con los cinco temas\n"
        "- Cambiado: la alarma de emergencia ahora parpadea en un "
        "patrón Morse SOS real (3 cortos, 3 largos, 3 cortos), para "
        "que siga siendo claramente reconocible como emergencia "
        "incluso con el tema Rojo activo\n"
        "- Cambiado: la señal LED de actualización disponible ahora "
        "parpadea en blanco en lugar de magenta\n"
        "- Novedad: se añadieron y explicaron los símbolos militar/"
        "gubernamental y de avión Heavy en la leyenda de colores de "
        "altitud\n"
        "- Corrección: la lluvia en el salvapantallas antes aparecía "
        "debajo del logo/reloj en lugar de encima\n"
        "- Novedad: la introducción de nombre de preset de ubicación "
        "ahora admite caracteres especiales (ej. \"Zürich\", \"São "
        "Paulo\")\n"
        "- Mejorado: se añadieron Â/Î/Ë/Û al teclado de caracteres "
        "especiales de direcciones\n"
        "- Corrección: se corrigió un desbordamiento en el diseño "
        "del teclado (la fila de acciones inferior quedaba cortada "
        "en el teclado de caracteres especiales ampliado)\n"
        "- Corrección: la lista de selección de idioma "
        "(configuración inicial + menú) ahora usa una altura de fila "
        "dinámica, para que no se produzca desbordamiento de "
        "pantalla ni siquiera con 7 idiomas";

    const char* const CHANGELOG_IT =
        "- Novità: aggiunto il portoghese (brasiliano) come settima "
        "lingua\n"
        "- Novità: aggiunti i temi colore \"Rosso\" e \"Viola\" - i "
        "tre pulsanti colore nel menu Visualizzazione radar sono "
        "stati uniti in un unico pulsante \"Colori\" che apre una "
        "schermata di selezione con tutti e cinque i temi\n"
        "- Modificato: l'allarme di emergenza ora lampeggia con un "
        "vero schema Morse SOS (3 brevi, 3 lunghi, 3 brevi), per "
        "rimanere chiaramente riconoscibile come emergenza anche con "
        "il tema Rosso attivo\n"
        "- Modificato: il segnale LED di aggiornamento disponibile "
        "ora lampeggia in bianco invece che in magenta\n"
        "- Novità: aggiunti e spiegati i simboli militare/governativo "
        "e aereo Heavy nella legenda dei colori altitudine\n"
        "- Correzione: la pioggia sullo screensaver prima si trovava "
        "sotto il logo/orologio invece che sopra\n"
        "- Novità: l'inserimento del nome dei preset di posizione "
        "ora supporta caratteri speciali (es. \"Zürich\", \"São "
        "Paulo\")\n"
        "- Migliorato: aggiunti Â/Î/Ë/Û alla tastiera di caratteri "
        "speciali per gli indirizzi\n"
        "- Correzione: risolto un problema di overflow nel layout "
        "della tastiera (la riga di azione inferiore veniva tagliata "
        "nella tastiera di caratteri speciali estesa)\n"
        "- Correzione: l'elenco di selezione della lingua "
        "(configurazione iniziale + menu) ora usa un'altezza di riga "
        "dinamica, così non si verifica overflow dello schermo "
        "nemmeno con 7 lingue";

    const char* const CHANGELOG_PT =
        "- Novo: português (brasileiro) adicionado como sétimo "
        "idioma\n"
        "- Novo: adicionados os temas de cor \"Vermelho\" e \"Roxo\" "
        "- os três botões de cor no menu Visualização do radar foram "
        "unificados em um único botão \"Cores\" que abre uma tela de "
        "seleção com os cinco temas\n"
        "- Alterado: o alarme de emergência agora pisca em um padrão "
        "Morse SOS real (3 curtos, 3 longos, 3 curtos), para "
        "continuar claramente reconhecível como emergência mesmo com "
        "o tema Vermelho ativo\n"
        "- Alterado: o sinal de LED de atualização disponível agora "
        "pisca em branco em vez de magenta\n"
        "- Novo: adicionados e explicados os símbolos militar/"
        "governamental e de avião Heavy na legenda de cores de "
        "altitude\n"
        "- Correção: a chuva na proteção de tela antes aparecia "
        "abaixo do logo/relógio em vez de acima\n"
        "- Novo: a entrada de nome de preset de localização agora "
        "suporta caracteres especiais (ex. \"Zürich\", \"São "
        "Paulo\")\n"
        "- Melhorado: adicionados Â/Î/Ë/Û ao teclado de caracteres "
        "especiais de endereços\n"
        "- Correção: corrigido um estouro no layout do teclado (a "
        "linha de ação inferior era cortada no teclado de caracteres "
        "especiais expandido)\n"
        "- Correção: a lista de seleção de idioma (configuração "
        "inicial + menu) agora usa uma altura de linha dinâmica, "
        "para que não ocorra estouro de tela nem mesmo com 7 "
        "idiomas";

    const char* const TABLE[CHANGELOG_LANG_COUNT] = {
        CHANGELOG_EN, CHANGELOG_DE, CHANGELOG_FR, CHANGELOG_TR, CHANGELOG_ES, CHANGELOG_IT, CHANGELOG_PT
    };
}

const char* changelogLatest() {
    uint8_t lang = SettingsStore::language();
    if (lang >= CHANGELOG_LANG_COUNT) lang = 0;
    return TABLE[lang];
}

}
