#include "changelog.h"
#include "settings_store.h"

namespace Config {

namespace {
    // Reihenfolge MUSS zu I18n::TABLES (i18n.cpp) und damit zu
    // SettingsStore::language() passen: EN, DE, FR, TR, ES, IT.
    constexpr uint8_t CHANGELOG_LANG_COUNT = 6;

    const char* const CHANGELOG_EN =
        "- Fix: the LED incorrectly showed only green instead of amber "
        "on the Amber color theme (real PWM color mixing instead of "
        "blinking/alternating)\n"
        "- New: subtle 3h weather preview in the top-right radar "
        "corner, only appears when the weather in 3h differs from now\n"
        "- New: subtle update-available indicator (pulsing exclamation "
        "mark) in the bottom-left radar corner, always visible once an "
        "update is ready\n"
        "- New: subtle \"nearest airport\" display (distance + bearing, "
        "in your configured IATA/ICAO format) in the top-left radar "
        "corner - tap it to add the airport directly as a location "
        "preset\n"
        "- New: \"Overlay\" display in the bottom-right radar corner - "
        "shows squawk watchlist, military/government, watchlist, and "
        "airline filter hits in rotation, each tappable to jump to the "
        "matching screen, can be turned off in the Radar Display menu "
        "(the update indicator is unaffected)\n"
        "- Fix: the Location Presets screen always showed the nearest "
        "airport in ICAO format, regardless of the configured IATA/ICAO "
        "preference\n"
        "- Improved: the altitude legend at the bottom of the radar is "
        "now tappable and shows an overlay explaining the colors in "
        "your configured unit\n"
        "- Improved: the route line now also shows which format is "
        "currently active (\"(IATA)\"/\"(ICAO)\")\n"
        "- New: on/off switch for the update LED signal (Menu > "
        "System)\n"
        "- Improved: reworked terminal boot sequence (no more cut-off "
        "text, \"Booting...\" title, line-by-line animation) - now "
        "only appears starting with the first restart after initial "
        "setup is complete";

    const char* const CHANGELOG_DE =
        "- Fix: Die LED zeigte beim Amber-Farbthema faelschlich nur "
        "Gruen statt Amber (echte PWM-Farbmischung statt Blinken/"
        "Alternieren)\n"
        "- Neu: Dezente 3h-Wettervorschau in der rechten oberen "
        "Radar-Ecke, erscheint nur wenn sich das Wetter in 3h "
        "aendert\n"
        "- Neu: Dezenter Update-Verfuegbar-Indikator (pulsierendes "
        "Ausrufezeichen) in der unteren linken Radar-Ecke, immer "
        "sichtbar sobald ein Update bereitsteht\n"
        "- Neu: Dezente \"Naechster Flughafen\"-Anzeige (Distanz+"
        "Peilung, im eingestellten IATA/ICAO-Format) in der oberen "
        "linken Radar-Ecke, antippbar zum direkten Anlegen als "
        "Standort-Preset\n"
        "- Neu: \"Overlay\"-Anzeige in der unteren rechten Radar-Ecke "
        "- zeigt abwechselnd Squawk-Wachposten-, Militaer-/Behoerden-, "
        "Watchlist- und Airline-Filter-Treffer, jeweils antippbar zur "
        "zugehoerigen Funktion, abschaltbar im Radar-Darstellungs-"
        "Menue (Update-Indikator bleibt davon unberuehrt)\n"
        "- Fix: Standort-Presets-Screen zeigte den naechsten Flughafen "
        "immer im ICAO-Format, unabhaengig von der eingestellten "
        "IATA/ICAO-Praeferenz\n"
        "- Verbessert: Hoehen-Legende am unteren Radarrand ist jetzt "
        "antippbar und zeigt ein Overlay mit Farberklaerung in der "
        "eingestellten Einheit\n"
        "- Verbessert: Routen-Anzeige zeigt jetzt zusaetzlich, welches "
        "Format gerade aktiv ist (\"(IATA)\"/\"(ICAO)\")\n"
        "- Neu: Ein/Aus-Schalter fuer das LED-Update-Signal (Menue > "
        "System)\n"
        "- Verbessert: Terminal-Boot-Sequenz ueberarbeitet (kein "
        "abgeschnittener Text, \"Booting...\"-Titel, zeilenweise "
        "Animation), erscheint jetzt erst ab dem ersten Neustart nach "
        "abgeschlossener Ersteinrichtung";

    const char* const CHANGELOG_FR =
        "- Correction : la LED n'affichait a tort que du vert au lieu "
        "d'ambre avec le theme de couleur Ambre (vrai melange de "
        "couleurs par PWM au lieu d'un clignotement/alternance)\n"
        "- Nouveau : previsions meteo a 3h discretes dans le coin "
        "superieur droit du radar, n'apparaissent que si la meteo dans "
        "3h differe de maintenant\n"
        "- Nouveau : indicateur discret de mise a jour disponible "
        "(point d'exclamation pulsant) dans le coin inferieur gauche "
        "du radar, toujours visible des qu'une mise a jour est prete\n"
        "- Nouveau : affichage discret de l'aeroport le plus proche "
        "(distance + relevement, au format IATA/ICAO configure) dans "
        "le coin superieur gauche du radar - toucher l'affichage "
        "l'ajoute directement comme preset de localisation\n"
        "- Nouveau : affichage \"Overlay\" dans le coin inferieur "
        "droit du radar - montre en alternance les correspondances de "
        "liste de surveillance squawk, militaire/gouvernemental, liste "
        "de surveillance et filtre de compagnie aerienne, chacune "
        "pouvant etre touchee pour acceder a l'ecran correspondant, "
        "desactivable dans le menu d'affichage radar (l'indicateur de "
        "mise a jour n'est pas concerne)\n"
        "- Correction : l'ecran des presets de localisation affichait "
        "toujours l'aeroport le plus proche au format ICAO, quelle que "
        "soit la preference IATA/ICAO configuree\n"
        "- Ameliore : la legende d'altitude en bas du radar est "
        "desormais tactile et affiche une fenetre explicative des "
        "couleurs dans l'unite configuree\n"
        "- Ameliore : la ligne de route indique maintenant aussi le "
        "format actuellement actif (\"(IATA)\"/\"(ICAO)\")\n"
        "- Nouveau : interrupteur pour le signal LED de mise a jour "
        "(Menu > Systeme)\n"
        "- Ameliore : sequence de demarrage type terminal revue (plus "
        "de texte coupe, titre \"Booting...\", animation ligne par "
        "ligne), n'apparait desormais qu'a partir du premier "
        "redemarrage une fois la configuration initiale terminee";

    const char* const CHANGELOG_TR =
        "- Duzeltme: Amber renk temasinda LED yanlislikla Amber yerine "
        "sadece Yesil gosteriyordu (yanip sonme/degisim yerine gercek "
        "PWM renk karisimi)\n"
        "- Yeni: Radarin sag ust kosesinde soluk 3 saatlik hava durumu "
        "onizlemesi, yalnizca 3 saat sonraki hava durumu simdikinden "
        "farkliysa gorunur\n"
        "- Yeni: Radarin sol alt kosesinde soluk guncelleme mevcut "
        "gostergesi (nabiz gibi atan unlem isareti), bir guncelleme "
        "hazir oldugunda her zaman gorunur\n"
        "- Yeni: Radarin sol ust kosesinde soluk \"En yakin havalimani\" "
        "gostergesi (mesafe + yon, ayarlanmis IATA/ICAO formatinda) - "
        "dokunarak havalimanini dogrudan konum on ayari olarak "
        "eklenebilir\n"
        "- Yeni: Radarin sag alt kosesinde \"Overlay\" gostergesi - "
        "squawk izleme listesi, askeri/resmi, izleme listesi ve "
        "havayolu filtresi eslesmelerini sirayla gosterir, her biri "
        "ilgili ekrana gitmek icin dokunulabilir, Radar Gorunumu "
        "menusunden kapatilabilir (guncelleme gostergesi bundan "
        "etkilenmez)\n"
        "- Duzeltme: Konum On Ayarlari ekrani, ayarlanmis IATA/ICAO "
        "tercihinden bagimsiz olarak en yakin havalimanini her zaman "
        "ICAO formatinda gosteriyordu\n"
        "- Iyilestirme: Radarin altindaki yukseklik lejandi artik "
        "dokunulabilir ve renkleri ayarlanmis birimde aciklayan bir "
        "katman gosteriyor\n"
        "- Iyilestirme: Rota satiri artik hangi formatin etkin oldugunu "
        "da gosteriyor (\"(IATA)\"/\"(ICAO)\")\n"
        "- Yeni: Guncelleme LED sinyali icin acma/kapama dugmesi (Menu "
        "> Sistem)\n"
        "- Iyilestirme: Terminal onyukleme dizisi yeniden tasarlandi "
        "(artik kesilen metin yok, \"Booting...\" basligi, satir satir "
        "animasyon), artik yalnizca ilk kurulum tamamlandiktan sonraki "
        "ilk yeniden baslatmadan itibaren gorunuyor";

    const char* const CHANGELOG_ES =
        "- Corrección: el LED mostraba incorrectamente solo verde en "
        "lugar de ámbar con el tema de color Ámbar (mezcla de color "
        "PWM real en lugar de parpadeo/alternancia)\n"
        "- Novedad: previsión meteorológica a 3h discreta en la "
        "esquina superior derecha del radar, solo aparece si el tiempo "
        "dentro de 3h difiere del actual\n"
        "- Novedad: indicador discreto de actualización disponible "
        "(signo de exclamación pulsante) en la esquina inferior "
        "izquierda del radar, siempre visible en cuanto hay una "
        "actualización lista\n"
        "- Novedad: indicación discreta del \"aeropuerto más cercano\" "
        "(distancia + rumbo, en el formato IATA/ICAO configurado) en "
        "la esquina superior izquierda del radar - tócala para "
        "añadirlo directamente como preset de ubicación\n"
        "- Novedad: indicación \"Overlay\" en la esquina inferior "
        "derecha del radar - muestra por turnos coincidencias de lista "
        "de vigilancia de squawk, militar/gubernamental, lista de "
        "vigilancia y filtro de aerolínea, cada una pulsable para ir a "
        "la pantalla correspondiente, se puede desactivar en el menú "
        "de visualización del radar (el indicador de actualización no "
        "se ve afectado)\n"
        "- Corrección: la pantalla de presets de ubicación mostraba "
        "siempre el aeropuerto más cercano en formato ICAO, "
        "independientemente de la preferencia IATA/ICAO configurada\n"
        "- Mejorado: la leyenda de altitud en la parte inferior del "
        "radar ahora es táctil y muestra una ventana explicando los "
        "colores en la unidad configurada\n"
        "- Mejorado: la línea de ruta ahora también muestra qué "
        "formato está activo (\"(IATA)\"/\"(ICAO)\")\n"
        "- Novedad: interruptor para la señal LED de actualización "
        "(Menú > Sistema)\n"
        "- Mejorado: secuencia de arranque tipo terminal renovada (ya "
        "no se corta el texto, título \"Booting...\", animación línea "
        "por línea), ahora solo aparece a partir del primer reinicio "
        "tras completar la configuración inicial";

    const char* const CHANGELOG_IT =
        "- Correzione: il LED mostrava erroneamente solo verde invece "
        "di ambra con il tema colore Ambra (vera miscelazione colore "
        "PWM invece di lampeggio/alternanza)\n"
        "- Novità: discreta anteprima meteo a 3h nell'angolo in alto a "
        "destra del radar, appare solo se il meteo tra 3h differisce "
        "da quello attuale\n"
        "- Novità: discreto indicatore di aggiornamento disponibile "
        "(punto esclamativo pulsante) nell'angolo in basso a sinistra "
        "del radar, sempre visibile non appena un aggiornamento è "
        "pronto\n"
        "- Novità: discreta indicazione \"Aeroporto più vicino\" "
        "(distanza + rilevamento, nel formato IATA/ICAO impostato) "
        "nell'angolo in alto a sinistra del radar - toccala per "
        "aggiungerlo direttamente come preset di posizione\n"
        "- Novità: indicazione \"Overlay\" nell'angolo in basso a "
        "destra del radar - mostra a rotazione le corrispondenze di "
        "lista di controllo squawk, militare/governativo, lista di "
        "controllo e filtro compagnia aerea, ciascuna toccabile per "
        "passare alla schermata corrispondente, disattivabile nel menu "
        "aspetto radar (l'indicatore di aggiornamento non ne è "
        "interessato)\n"
        "- Correzione: la schermata dei preset di posizione mostrava "
        "sempre l'aeroporto più vicino in formato ICAO, "
        "indipendentemente dalla preferenza IATA/ICAO impostata\n"
        "- Migliorato: la legenda altitudine in basso sul radar è ora "
        "toccabile e mostra una finestra che spiega i colori "
        "nell'unità impostata\n"
        "- Migliorato: la riga della rotta ora mostra anche quale "
        "formato è attivo (\"(IATA)\"/\"(ICAO)\")\n"
        "- Novità: interruttore per il segnale LED di aggiornamento "
        "(Menu > Sistema)\n"
        "- Migliorato: sequenza di avvio in stile terminale rivista "
        "(niente più testo tagliato, titolo \"Booting...\", animazione "
        "riga per riga), ora appare solo a partire dal primo riavvio "
        "dopo il completamento della configurazione iniziale";

    const char* const TABLE[CHANGELOG_LANG_COUNT] = {
        CHANGELOG_EN, CHANGELOG_DE, CHANGELOG_FR, CHANGELOG_TR, CHANGELOG_ES, CHANGELOG_IT
    };
}

const char* changelogLatest() {
    uint8_t lang = SettingsStore::language();
    if (lang >= CHANGELOG_LANG_COUNT) lang = 0;
    return TABLE[lang];
}

}
