#include "changelog.h"
#include "settings_store.h"

namespace Config {

namespace {
    // Reihenfolge MUSS zu I18n::TABLES (i18n.cpp) und damit zu
    // SettingsStore::language() passen: EN, DE, FR, TR, ES, IT, PT, NL.
    constexpr uint8_t CHANGELOG_LANG_COUNT = 8;

    const char* const CHANGELOG_EN =
        "- New: the \"SD card missing\" screen now shows concrete "
        "troubleshooting steps (reformat with the official SD Card "
        "Formatter first, try a different card if that doesn't help) "
        "instead of just \"insert card and restart\"\n"
        "- New: the live traffic screen is now reachable directly from "
        "the radar screen - a new, always-visible target icon in the "
        "bottom-left corner opens it with a tap (previously buried deep "
        "in the menu and practically never found). The update-available "
        "indicator that used to sit there as a pulsing \"!\" now pulses "
        "as a small red dot on the Menu button instead\n"
        "- Fix: the red dot on the \"Flight Logbook\" menu entries used "
        "to look like an alarm after the 24h safety auto-off - it now "
        "correctly shows whether the logbook is actively recording, and "
        "disappears immediately when turned off\n"
        "- Fix: the Units setting (Menu > Region & Language > Units: "
        "Auto/Metric/Imperial) had no effect at all - it now actually "
        "applies: the aircraft detail panel shows only the selected unit "
        "for altitude/speed/distance instead of always both, and clocks "
        "(header and \"first seen\" in the detail panel) switch between "
        "24-hour and 12-hour AM/PM format accordingly\n"
        "- Fix: \"First seen\"/\"Seen for\" in the aircraft detail panel "
        "are now phrased unambiguously (e.g. \"First seen at 16:40:25\" "
        "instead of just \":16:40:25\", \"Seen for 10min 20s\" instead "
        "of the ambiguous \"10:20\")";

    const char* const CHANGELOG_DE =
        "- Neu: Der \"SD-Karte fehlt\"-Bildschirm zeigt jetzt konkrete "
        "Troubleshooting-Hinweise (zuerst mit dem offiziellen SD Card "
        "Formatter neu formatieren, falls das nicht hilft eine andere "
        "Karte probieren) statt nur \"Karte einlegen und neu starten\"\n"
        "- Neu: Der Live-Verkehr-Screen ist jetzt direkt vom Radarscreen "
        "aus erreichbar - ein neues, dauerhaft sichtbares "
        "Zielmarkierungs-Symbol unten links in der Radar-Ecke öffnet ihn "
        "per Antippen (vorher nur tief im Menü versteckt und praktisch "
        "nie gefunden). Die Update-verfügbar-Anzeige, die vorher dort als "
        "pulsierendes \"!\" saß, pulsiert jetzt stattdessen als kleiner "
        "roter Punkt am Menü-Button\n"
        "- Fix: Der rote Punkt bei \"Flugbuch\" im Menü wirkte nach der "
        "24h-Sicherheitsabschaltung fälschlich wie ein Alarm - er zeigt "
        "jetzt korrekt an, ob das Flugbuch gerade aktiv aufzeichnet, und "
        "verschwindet sofort beim Ausschalten\n"
        "- Fix: Die Einstellung \"Einheiten\" (Menü > Land/Region > "
        "Einheiten: Auto/Metrisch/Imperial) hatte bisher keinerlei "
        "Wirkung - sie wirkt sich jetzt tatsächlich aus: Höhe/"
        "Geschwindigkeit/Distanz im Flugzeug-Detailscreen zeigen nur noch "
        "die eingestellte Einheit statt immer beide, und Uhrzeiten "
        "(Kopfzeile sowie \"Erstmals gesehen\" im Detailscreen) wechseln "
        "entsprechend zwischen 24-Stunden- und 12-Stunden-Format mit "
        "AM/PM\n"
        "- Fix: \"Erstmals gesehen\"/\"Sichtbar seit\" im Flugzeug-"
        "Detailscreen sind jetzt eindeutig formuliert (z.B. \"Erstmals "
        "gesehen um 16:40:25 Uhr\" statt nur \":16:40:25\", \"Sichtbar "
        "seit 10min 20s\" statt der bisherigen mehrdeutigen \"10:20\")";

    const char* const CHANGELOG_FR =
        "- Nouveau : l'écran « carte SD manquante » affiche désormais des "
        "conseils de dépannage concrets (reformater d'abord avec "
        "l'utilitaire officiel SD Card Formatter, essayer une autre "
        "carte si cela ne suffit pas) au lieu de simplement « insérez la "
        "carte et redémarrez »\n"
        "- Nouveau : l'écran du trafic en direct est désormais "
        "accessible directement depuis l'écran radar - une nouvelle "
        "icône de cible, toujours visible, dans le coin inférieur gauche "
        "l'ouvre d'un simple appui (auparavant enfoui profondément dans "
        "le menu et pratiquement jamais trouvé). L'indicateur de mise à "
        "jour disponible, qui occupait auparavant cet emplacement sous "
        "forme de « ! » clignotant, clignote désormais à la place sous "
        "forme d'un petit point rouge sur le bouton Menu\n"
        "- Correction : le point rouge sur les entrées « Carnet de vol » "
        "du menu ressemblait à tort à une alarme après l'arrêt "
        "automatique de sécurité (24h) - il indique désormais "
        "correctement si le carnet de vol enregistre activement, et "
        "disparaît immédiatement à la désactivation\n"
        "- Correction : le réglage « Unités » (Menu > Région et langue > "
        "Unités : Auto/Métrique/Impérial) n'avait jusqu'ici aucun effet - "
        "il s'applique désormais réellement : le panneau de détails de "
        "l'avion n'affiche plus que l'unité choisie pour l'altitude/la "
        "vitesse/la distance au lieu des deux à la fois, et les horloges "
        "(en-tête et « vu pour la première fois » dans le panneau de "
        "détails) basculent en conséquence entre le format 24 heures et "
        "le format 12 heures AM/PM\n"
        "- Correction : « Vu pour la première fois »/« Visible depuis » "
        "dans le panneau de détails de l'avion sont désormais formulés "
        "sans ambiguïté (par ex. « Vu pour la première fois à 16:40:25 » "
        "au lieu de simplement « : 16:40:25 », « Visible depuis 10min "
        "20s » au lieu du « 10:20 » ambigu)";

    const char* const CHANGELOG_TR =
        "- Yeni: \"SD kart eksik\" ekranı artık somut sorun giderme "
        "ipuçları gösteriyor (önce resmi SD Card Formatter ile yeniden "
        "biçimlendirin, bu işe yaramazsa başka bir kart deneyin), sadece "
        "\"kartı takın ve yeniden başlatın\" yerine\n"
        "- Yeni: Canlı trafik ekranı artık doğrudan radar ekranından "
        "erişilebiliyor - radar köşesinin sol altındaki yeni, her zaman "
        "görünen hedef işareti simgesine dokunarak açılıyor (önceden "
        "menünün derinliklerinde saklıydı ve neredeyse hiç "
        "bulunamıyordu). Daha önce orada yanıp sönen bir \"!\" olarak "
        "duran güncelleme mevcut göstergesi, artık bunun yerine Menü "
        "düğmesinde küçük, yanıp sönen kırmızı bir nokta olarak "
        "gösteriliyor\n"
        "- Düzeltme: Menüdeki \"Uçuş Defteri\" girişlerindeki kırmızı "
        "nokta, 24 saatlik otomatik kapanmadan sonra yanlışlıkla bir "
        "alarm gibi görünüyordu - artık uçuş defterinin şu anda etkin "
        "şekilde kayıt yapıp yapmadığını doğru şekilde gösteriyor ve "
        "kapatıldığında hemen kayboluyor\n"
        "- Düzeltme: \"Birimler\" ayarı (Menü > Bölge ve Dil > Birimler: "
        "Otomatik/Metrik/İngiliz) şimdiye kadar hiçbir etkisi yoktu - "
        "artık gerçekten uygulanıyor: uçak detay panelindeki irtifa/hız/"
        "mesafe artık her zaman ikisini birden değil, yalnızca seçili "
        "birimi gösteriyor ve saatler (üst bilgi ile detay panelindeki "
        "\"ilk görülme\") buna göre 24 saat ile AM/PM'li 12 saat biçimi "
        "arasında geçiş yapıyor\n"
        "- Düzeltme: Uçak detay panelindeki \"İlk görülme\"/\"Görünürlük "
        "süresi\" artık net bir şekilde ifade ediliyor (örn. sadece "
        "\":16:40:25\" yerine \"İlk görülme saati: 16:40:25\", belirsiz "
        "\"10:20\" yerine \"Görünürlük süresi 10min 20s\")";

    const char* const CHANGELOG_ES =
        "- Novedad: la pantalla \"falta la tarjeta SD\" ahora muestra "
        "consejos de solución de problemas concretos (primero "
        "reformatear con el SD Card Formatter oficial, si eso no ayuda "
        "probar con otra tarjeta) en lugar de solo \"inserta la tarjeta "
        "y reinicia\"\n"
        "- Novedad: la pantalla de tráfico en vivo ahora es accesible "
        "directamente desde la pantalla de radar - un nuevo icono de "
        "diana, siempre visible, en la esquina inferior izquierda la "
        "abre con solo tocarlo (antes escondido en lo profundo del menú "
        "y prácticamente nunca encontrado). El indicador de "
        "actualización disponible, que antes ocupaba ese lugar como un "
        "\"!\" parpadeante, ahora parpadea en su lugar como un pequeño "
        "punto rojo en el botón de Menú\n"
        "- Corrección: el punto rojo en las entradas \"Cuaderno de "
        "vuelo\" del menú parecía erróneamente una alarma tras la "
        "desconexión automática de seguridad (24h) - ahora indica "
        "correctamente si el cuaderno de vuelo está grabando "
        "activamente, y desaparece de inmediato al desactivarlo\n"
        "- Corrección: el ajuste \"Unidades\" (Menú > Región e idioma > "
        "Unidades: Auto/Métrico/Imperial) no tenía ningún efecto hasta "
        "ahora - ahora sí se aplica realmente: el panel de detalles del "
        "avión muestra solo la unidad seleccionada para altitud/"
        "velocidad/distancia en lugar de mostrar siempre ambas, y los "
        "relojes (cabecera y \"visto por primera vez\" en el panel de "
        "detalles) cambian en consecuencia entre formato de 24 horas y "
        "de 12 horas con AM/PM\n"
        "- Corrección: \"Visto por primera vez\"/\"Visible desde hace\" "
        "en el panel de detalles del avión ahora están formulados sin "
        "ambigüedad (por ej. \"Visto por primera vez a las 16:40:25\" en "
        "lugar de solo \": 16:40:25\", \"Visible desde hace 10min 20s\" "
        "en lugar del ambiguo \"10:20\")";

    const char* const CHANGELOG_IT =
        "- Novità: la schermata \"scheda SD mancante\" ora mostra "
        "consigli di risoluzione dei problemi concreti (prima "
        "riformattare con l'SD Card Formatter ufficiale, se non aiuta "
        "provare un'altra scheda) invece di semplicemente \"inserisci la "
        "scheda e riavvia\"\n"
        "- Novità: la schermata del traffico in tempo reale è ora "
        "raggiungibile direttamente dalla schermata radar - una nuova "
        "icona a mirino, sempre visibile, nell'angolo in basso a "
        "sinistra la apre con un tocco (prima nascosta in profondità nel "
        "menu e praticamente mai trovata). L'indicatore di aggiornamento "
        "disponibile, che prima occupava quel posto come \"!\" "
        "lampeggiante, ora lampeggia invece come un piccolo punto rosso "
        "sul pulsante Menu\n"
        "- Correzione: il punto rosso sulle voci \"Diario di volo\" nel "
        "menu sembrava erroneamente un allarme dopo lo spegnimento "
        "automatico di sicurezza (24h) - ora mostra correttamente se il "
        "diario di volo sta registrando attivamente, e scompare subito "
        "alla disattivazione\n"
        "- Correzione: l'impostazione \"Unità\" (Menu > Regione e lingua "
        "> Unità: Auto/Metrico/Imperiale) finora non aveva alcun effetto "
        "- ora si applica davvero: il pannello dei dettagli dell'aereo "
        "mostra solo l'unità impostata per altitudine/velocità/distanza "
        "invece di entrambe sempre, e gli orologi (intestazione e "
        "\"visto per la prima volta\" nel pannello dei dettagli) passano "
        "di conseguenza tra formato 24 ore e formato 12 ore con AM/PM\n"
        "- Correzione: \"Visto per la prima volta\"/\"Visibile da\" nel "
        "pannello dei dettagli dell'aereo sono ora formulati in modo "
        "inequivocabile (es. \"Visto per la prima volta alle 16:40:25\" "
        "invece di solo \": 16:40:25\", \"Visibile da 10min 20s\" invece "
        "dell'ambiguo \"10:20\")";

    const char* const CHANGELOG_PT =
        "- Novo: a tela \"cartão SD ausente\" agora mostra dicas "
        "concretas de solução de problemas (primeiro reformatar com o "
        "SD Card Formatter oficial, se isso não ajudar experimentar "
        "outro cartão) em vez de apenas \"insira o cartão e reinicie\"\n"
        "- Novo: a tela de tráfego ao vivo agora é acessível diretamente "
        "pela tela de radar - um novo ícone de alvo, sempre visível, no "
        "canto inferior esquerdo a abre ao toque (antes escondido nas "
        "profundezas do menu e praticamente nunca encontrado). O "
        "indicador de atualização disponível, que antes ficava ali como "
        "um \"!\" piscante, agora pisca em vez disso como um pequeno "
        "ponto vermelho no botão Menu\n"
        "- Correção: o ponto vermelho nas entradas \"Diário de bordo\" "
        "do menu parecia erroneamente um alarme após o desligamento "
        "automático de segurança (24h) - agora mostra corretamente se o "
        "diário de bordo está gravando ativamente, e desaparece "
        "imediatamente ao ser desativado\n"
        "- Correção: a configuração \"Unidades\" (Menu > Região e idioma "
        "> Unidades: Auto/Métrico/Imperial) não tinha nenhum efeito até "
        "agora - agora ela realmente se aplica: o painel de detalhes da "
        "aeronave mostra apenas a unidade selecionada para altitude/"
        "velocidade/distância em vez de sempre mostrar ambas, e os "
        "relógios (cabeçalho e \"visto pela primeira vez\" no painel de "
        "detalhes) alternam de acordo entre o formato de 24 horas e o de "
        "12 horas com AM/PM\n"
        "- Correção: \"Visto pela primeira vez\"/\"Visível há\" no "
        "painel de detalhes da aeronave agora estão formulados de forma "
        "inequívoca (ex. \"Visto pela primeira vez às 16:40:25\" em vez "
        "de apenas \": 16:40:25\", \"Visível há 10min 20s\" em vez do "
        "ambíguo \"10:20\")";

    const char* const CHANGELOG_NL =
        "- Nieuw: het \"SD-kaart ontbreekt\"-scherm toont nu concrete "
        "tips voor probleemoplossing (eerst opnieuw formatteren met de "
        "officiële SD Card Formatter, als dat niet helpt een andere "
        "kaart proberen) in plaats van alleen \"kaart plaatsen en "
        "opnieuw starten\"\n"
        "- Nieuw: het live-verkeersscherm is nu rechtstreeks vanaf het "
        "radarscherm bereikbaar - een nieuw, altijd zichtbaar doelwit-"
        "symbool linksonder in de radarhoek opent het met een tik "
        "(voorheen diep verstopt in het menu en vrijwel nooit gevonden). "
        "De update-beschikbaar-indicator, die daar voorheen als "
        "knipperende \"!\" stond, knippert nu in plaats daarvan als een "
        "klein rood puntje op de Menu-knop\n"
        "- Fix: het rode puntje bij \"Logboek\" in het menu leek ten "
        "onrechte op een alarm nadat het logboek automatisch was "
        "uitgeschakeld (24u) - het toont nu correct of het logboek "
        "actief aan het opnemen is, en verdwijnt meteen bij het "
        "uitschakelen\n"
        "- Fix: de instelling \"Eenheden\" (Menu > Regio en taal > "
        "Eenheden: Auto/Metrisch/Imperiaal) had tot nu toe geen effect - "
        "hij werkt nu daadwerkelijk: het detailpaneel van het vliegtuig "
        "toont voor hoogte/snelheid/afstand nu alleen nog de ingestelde "
        "eenheid in plaats van altijd beide, en klokken (koptekst en "
        "\"voor het eerst gezien\" in het detailpaneel) wisselen "
        "dienovereenkomstig tussen 24-uurs- en 12-uursformaat met AM/PM\n"
        "- Fix: \"Voor het eerst gezien\"/\"Zichtbaar sinds\" in het "
        "detailpaneel van het vliegtuig zijn nu ondubbelzinnig "
        "geformuleerd (bijv. \"Voor het eerst gezien om 16:40:25 uur\" "
        "in plaats van alleen \": 16:40:25\", \"Zichtbaar sinds 10min "
        "20s\" in plaats van het dubbelzinnige \"10:20\")";

    const char* const TABLE[CHANGELOG_LANG_COUNT] = {
        CHANGELOG_EN, CHANGELOG_DE, CHANGELOG_FR, CHANGELOG_TR, CHANGELOG_ES, CHANGELOG_IT, CHANGELOG_PT, CHANGELOG_NL
    };
}

const char* changelogLatest() {
    uint8_t lang = SettingsStore::language();
    if (lang >= CHANGELOG_LANG_COUNT) lang = 0;
    return TABLE[lang];
}

}
